C:\xampp\htdocs\splitwisebackend\splitwise\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\xampp\htdocs\splitwisebackend\splitwise\__init__.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Bad Request: /api/createGroup
"POST /api/createGroup HTTP/1.1" 400 117
"POST /api/createGroup HTTP/1.1" 200 40
C:\xampp\htdocs\splitwisebackend\expense\views.py changed, reloading.
Watching for file changes with StatReloader
Unauthorized: /api/createGroup
"POST /api/createGroup HTTP/1.1" 401 58
C:\xampp\htdocs\splitwisebackend\expense\views.py changed, reloading.
Watching for file changes with StatReloader
C:\xampp\htdocs\splitwisebackend\expense\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /api/createGroup
Traceback (most recent call last):
  File "C:\Users\Lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "C:\Users\Lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "C:\Users\Lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\rest_framework\views.py", line 331, in check_permissions
    for permission in self.get_permissions():
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\rest_framework\views.py", line 278, in get_permissions
    return [permission() for permission in self.permission_classes]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'BasePermissionMetaclass' object is not iterable
"POST /api/createGroup HTTP/1.1" 500 102702
C:\xampp\htdocs\splitwisebackend\expense\views.py changed, reloading.
Watching for file changes with StatReloader
Unauthorized: /api/createGroup
"POST /api/createGroup HTTP/1.1" 401 58
"POST /api/login HTTP/1.1" 200 550
Bad Request: /api/createGroup
"POST /api/createGroup HTTP/1.1" 400 61
"POST /api/createGroup HTTP/1.1" 200 40
C:\xampp\htdocs\splitwisebackend\expense\views.py changed, reloading.
Watching for file changes with StatReloader
C:\xampp\htdocs\splitwisebackend\expense\views.py changed, reloading.
Watching for file changes with StatReloader
C:\xampp\htdocs\splitwisebackend\expense\views.py changed, reloading.
Watching for file changes with StatReloader
"POST /api/login HTTP/1.1" 200 550
C:\xampp\htdocs\splitwisebackend\splitwise\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\xampp\htdocs\splitwisebackend\splitwise\settings.py changed, reloading.
Watching for file changes with StatReloader
